import { useNavigate } from 'react-router-dom'
import { Sparkles, Zap, Target, BarChart3, ArrowRight, CheckCircle2, Star } from 'lucide-react'
import { useDarkMode } from '../hooks/useDarkMode'
import { Sun, Moon } from 'lucide-react'

const features = [
  { icon: Sparkles, title: 'AI-Powered Questions', desc: 'Get role-specific questions generated by GPT-4, tailored to your experience level and target skills.', color: 'text-indigo-500', bg: 'bg-indigo-50 dark:bg-indigo-500/10' },
  { icon: Target,   title: 'Role-Based Prep',     desc: 'Choose from 20+ engineering roles. Questions adapt to your exact job target and tech stack.', color: 'text-violet-500', bg: 'bg-violet-50 dark:bg-violet-500/10' },
  { icon: Zap,      title: 'Mock Interviews',      desc: 'Practice under real conditions with timed sessions, one question at a time.', color: 'text-blue-500', bg: 'bg-blue-50 dark:bg-blue-500/10' },
  { icon: BarChart3, title: 'Track Progress',      desc: 'Review your history, save key questions, and measure improvement over time.', color: 'text-emerald-500', bg: 'bg-emerald-50 dark:bg-emerald-500/10' },
]

const testimonials = [
  { name: 'Sarah K.', role: 'SWE @ Google', text: 'Landed my dream job after 2 weeks of prep with InterviewAI. The questions were spot-on.', stars: 5 },
  { name: 'Marcus T.', role: 'Frontend Dev @ Stripe', text: 'The role-specific questions saved me hours of research. Highly recommend.', stars: 5 },
  { name: 'Priya M.', role: 'Data Scientist @ Meta', text: 'Mock interview mode is a game changer. Felt so prepared walking in.', stars: 5 },
]

export default function Landing() {
  const navigate = useNavigate()
  const { dark, toggle } = useDarkMode()

  return (
    <div className="min-h-screen bg-white dark:bg-[#0a0a0f]">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 border-b border-slate-200 dark:border-white/5 bg-white/80 dark:bg-[#0a0a0f]/80 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-slate-900 dark:text-white">InterviewAI</span>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={toggle} className="btn-ghost p-2 rounded-xl">
              {dark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </button>
            <button onClick={() => navigate('/login')} className="btn-secondary px-4 py-2 text-sm">Sign In</button>
            <button onClick={() => navigate('/signup')} className="btn-primary px-4 py-2 text-sm">Get Started</button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden pt-24 pb-20 px-6">
        <div className="absolute inset-0 bg-mesh pointer-events-none" />
        <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-indigo-500/5 dark:bg-indigo-500/8 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-4xl mx-auto text-center relative">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/20 text-indigo-700 dark:text-indigo-300 text-sm font-medium mb-8 animate-fade-up">
            <Sparkles className="w-3.5 h-3.5" />
            Powered by GPT-4
          </div>

          <h1 className="text-5xl md:text-7xl font-extrabold text-slate-900 dark:text-white leading-tight tracking-tight mb-6 animate-fade-up animate-delay-100">
            Ace Your Next<br />
            <span className="gradient-text">Technical Interview</span>
          </h1>

          <p className="text-xl text-slate-500 dark:text-white/50 max-w-2xl mx-auto mb-10 leading-relaxed animate-fade-up animate-delay-200">
            AI-generated interview questions tailored to your role, skills, and experience level. Practice smarter, not harder.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-fade-up animate-delay-300">
            <button onClick={() => navigate('/signup')} className="btn-primary px-8 py-3.5 text-base w-full sm:w-auto">
              Get Started Free <ArrowRight className="w-4 h-4" />
            </button>
            <button onClick={() => navigate('/login')} className="btn-secondary px-8 py-3.5 text-base w-full sm:w-auto">
              Sign In
            </button>
          </div>

          <div className="flex items-center justify-center gap-6 mt-10 text-sm text-slate-400 dark:text-white/30 animate-fade-up animate-delay-300">
            {['No credit card required', 'Free to start', '10k+ users'].map(t => (
              <span key={t} className="flex items-center gap-1.5">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> {t}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 px-6 bg-slate-50 dark:bg-[#0d0d14]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-4">Everything you need to prepare</h2>
            <p className="text-slate-500 dark:text-white/40 text-lg max-w-xl mx-auto">From AI question generation to mock interviews — all in one place.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">
            {features.map(({ icon: Icon, title, desc, color, bg }) => (
              <div key={title} className="card p-6 hover:shadow-md dark:hover:border-white/20 transition-all duration-200 group">
                <div className={`w-10 h-10 rounded-xl ${bg} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                  <Icon className={`w-5 h-5 ${color}`} />
                </div>
                <h3 className="font-semibold text-slate-900 dark:text-white mb-2">{title}</h3>
                <p className="text-sm text-slate-500 dark:text-white/40 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-4">Loved by engineers</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {testimonials.map(t => (
              <div key={t.name} className="card p-6">
                <div className="flex gap-0.5 mb-4">
                  {Array.from({ length: t.stars }).map((_, i) => (
                    <Star key={i} className="w-4 h-4 fill-amber-400 text-amber-400" />
                  ))}
                </div>
                <p className="text-slate-600 dark:text-white/60 text-sm leading-relaxed mb-5">"{t.text}"</p>
                <div>
                  <p className="font-semibold text-slate-900 dark:text-white text-sm">{t.name}</p>
                  <p className="text-xs text-slate-400 dark:text-white/30">{t.role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6 bg-slate-50 dark:bg-[#0d0d14]">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-4">Ready to start preparing?</h2>
          <p className="text-slate-500 dark:text-white/40 mb-8">Join thousands of engineers who landed their dream jobs.</p>
          <button onClick={() => navigate('/signup')} className="btn-primary px-10 py-3.5 text-base">
            Get Started Free <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-200 dark:border-white/5 py-8 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded-md bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center">
              <Sparkles className="w-3 h-3 text-white" />
            </div>
            <span className="text-sm font-semibold text-slate-700 dark:text-white/60">InterviewAI</span>
          </div>
          <p className="text-xs text-slate-400 dark:text-white/25">© 2026 InterviewAI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
